RedHatInsights/subscription-inventory-ui

- src/components/ProductsTable/ProductsTable.tsx
- src/components/ProductsTable/__tests__/ProductsTable.test.tsx
- src/components/ProductsTable/__tests__/__snapshots__/ProductsTable.test.tsx.snap
We forgot to add an empty state for when a search is typed and no results are found.  This adds the same "No Results" view that is in our other app.
> Show empty state when no search results are found

- src/components/GettingStartedCard/GettingStartedCard.tsx
- src/components/GettingStartedCard/__tests__/GettingStartedCard.test.tsx
- src/components/GettingStartedCard/__tests__/__snapshots__/GettingStartedCard.test.tsx.snap
- src/components/GettingStartedCard/index.ts
- src/pages/SubscriptionInventoryPage/SubscriptionInventoryPage.tsx
- src/pages/SubscriptionInventoryPage/__tests__/__snapshots__/SubscriptionInventoryPage.test.tsx.snap
[TEAMNADO-3379](https://issues.redhat.com/browse/TEAMNADO-3379) 
Adds the getting started resources
I tried to DRY the new component as best I could with additional components and interfaces.  But I'm new-ish to React and very new to Typescript.  Any suggestions are welcome!
> TEAMNADO-3379 - Add getting started resources

- src/components/ProductsTable/ProductsTable.tsx
Adds "No Results Found" when Filters have 0 subscriptions
> TEAMNADO-3874: Bug: Blank view does not show appropriate message

- src/components/SubscriptionTable/SubscriptionTable.tsx
> TEAMNADO-3922 : Display dates in provided time zone from API, not user's TZ

- package-lock.json
- package.json
> TEAMNADO-3858: CVE-2022-31129 moment: inefficient parsing algorithim resulting in DoS [services-subscription-central-default]

- src/components/ProductsTable/ProductsTable.tsx
- src/components/ProductsTable/__tests__/ProductsTable.test.tsx
- src/components/ProductsTable/__tests__/__snapshots__/ProductsTable.test.tsx.snap
- src/pages/DetailsPage/DetailsPage.tsx
- src/pages/DetailsPage/__tests__/__snapshots__/DetailsPage.test.tsx.snap
Removed unitOfMeasure column from products table, cleaned sorting logic, updated Unit of Measure to Capacity for SKU details page, cleaned tests
> TEAMNADO-3884: Change Unit of Measure to Capacity

- build_deploy.sh
- pr_check.sh
After rereading the document I believe this is what the application name needs to be set to for this application. We will find out for sure later but the next step makes it seem like it is supposed to be the containing folder
@cowanrc
> BUG - Incorrect application name

- src/hooks/__tests__/useUser.test.tsx
- src/hooks/useUser.ts
- src/pages/DetailsPage/__tests__/DetailsPage.test.tsx
- src/pages/NoPermissionsPage/__tests__/NoPermissionsPage.test.tsx
- src/pages/OopsPage/__tests__/OopsPage.test.tsx
- src/pages/SubscriptionInventoryPage/__tests__/SubscriptionInventoryPage.test.tsx
Removed all instances of SCA from sub inventory, as it wasn't being used at all.
> TEAMNADO-3999: Investigate the calls to v1/organization

- deploy/frontend.yaml
> add deployment spec

- deploy/frontend.yaml
> Fix image ref

- deploy/frontend.yaml
> Correct name and path

- package.json
- src/pages/SubscriptionInventoryPage/SubscriptionInventoryPage.tsx
- src/pages/SubscriptionInventoryPage/__tests__/__snapshots__/SubscriptionInventoryPage.test.tsx.snap
Resolves TEAMNADO-4211 by only rendering the error page once
> TEAMNADO-4211 only show page unavailable once

- src/components/ExportSubscriptions/ExportSubscriptions.tsx
- src/components/ExportSubscriptions/__tests__/ExportSusbcriptions.test.tsx
- src/components/ExportSubscriptions/index.ts
- src/components/ProductsTable/ProductsTable.tsx
- src/components/ProductsTable/__tests__/ProductsTable.test.tsx
- src/hooks/__tests__/useExportSubscriptions.test.tsx
- src/hooks/useExportSubscriptions.ts
Adds export button to download a csv of subscriptions
> TEAMNADO-4402 - Download .csv of subscriptions

- src/components/SubscriptionTable/SubscriptionTable.tsx
- src/components/SubscriptionTable/__tests__/SubscriptionTable.test.tsx
- src/pages/DetailsPage/__tests__/DetailsPage.test.tsx
Release TEAMNADO-4699 to prod stable
> Backfill prod-stable to main

- config/dev.webpack.config.js
part of [RHCLOUD-25607](https://issues.redhat.com/browse/RHCLOUD-25607) . Need to change AppUrl in each of the subscriptions apps to be /subscriptions/<app-name> instead of /insights/subscriptions/<app-name>
> add new appUrl

- src/components/PurchaseModal/PurchaseModal.tsx
This updates the sales link from access.redhat to www.redhat
> TEAMNADO-5638: Update contact sales link

- src/pages/DetailsPage/DetailsPage.tsx
- src/pages/DetailsPage/__tests__/DetailsPage.test.tsx
This removes the subscriptionInventory.detailsTable feature flag, as it has been turned on in all environments for months. After this is deployed we can delete the flag in each env
> TEAMNADO-6950: Remove feature flag

- src/components/Widgets/SubscriptionsWidget.scss
Vertically center Empty state
Jira: https://issues.redhat.com/browse/RHCLOUD-32809
Old
New
> Update empty state styling

- .tekton/subscription-inventory-ui-pull-request.yaml
- .tekton/subscription-inventory-ui-push.yaml
adding rpms signature scan to pull request and push yamls
No testing needed
> TEAMNADO-7820 adding rpms signature scan to tekton pipeline

- src/components/GettingStartedCard/GettingStartedCard.tsx
- src/components/GettingStartedCard/__tests__/GettingStartedCard.test.tsx
https://issues.redhat.com/browse/RHCLOUD-36258
> Update GettingStartedCard.tsx to default to open

- src/components/Widgets/SubscriptionsWidget.scss
- src/components/Widgets/SubscriptionsWidget.tsx
Jira: https://issues.redhat.com/browse/RHCLOUD-37476
- Open links in same window
- Add padding around alerts
Old
New
> update subscription widget styling

- src/components/ProductsTable/ProductsTable.tsx
- src/components/ProductsTable/__tests__/ProductsTable.test.tsx
> TUSC-39 Remove ProductLine from sub inventory table

- .tekton/subscription-inventory-ui-pull-request.yaml
- .tekton/subscription-inventory-ui-push.yaml
https://issues.redhat.com/browse/KONFLUX-2264
> Add shell and unicode sast pipeline tasks
